### ISSUE TITLE
Undesirable toolbar displaying when focus on a form select element

### ISSUE THREAD

**Issue by adrianorsouza** [daviferreira/medium-editor#552] opened 2015-04-11 06:31 UTC
To produce this error is needed to set these options `staticToolbar` and `stickyToolbar` to `true` then in your html create a select element with some options in it then click in the select element and keep the focus in it without choosing an option, on blur the toolbar will shown.

This error is encountered in Chrome 41+, Safari 7+ and Opera 28

Here is how to demostrate this error: https://jsfiddle.net/3dmfpx6w/

**Comment by nmielnik** [comment] 2015-04-11 16:03
@adrianorsouza I believe this should be fixed as of v4.4.0.

I tried pulling down the latest medium-editor code from master and adding it to your jsfiddle and I believe the issue should no longer happen.

Thank you for pointing this out and opening the fiddle, let us know if you are still able to reproduce it so we can re-open the issue and investigate further.

**Closed by nmielnik** 2015-04-11 16:03 UTC

**Comment by adrianorsouza** [comment] 2015-04-11 18:26
@nmielnik Thanks for updates, the problem seems to be fixed, however, after I updated to 4.4.0 I noticed that the toolbar now behaves the same as I set an option `staticToolbar: false` in 4.3.0. which did not have that conflict with focus on select elements.

In 4.3.0 the option `staticToolbar: true` always displayed the toolbar when editor element receives focus, this behaviour was pretty usefull for UX when using the [table][tables] extension, so the user don't need to type a text and make a text selection in order to display the toolbar to add tables.

In 4.4.0 the error I pointed out earlier gone, although it is not possible to always display the toolbar by setting the `staticToolbar` option as it was possible in 4.3.0.

I'm not clear whether the option `staticToolbar` is intend to always display the toolbar relative to the editor element when the editor is focused or only display the toolbar relative to the element when is made a text selection.

[tables]: https://github.com/daviferreira/medium-editor-tables

**Comment by nmielnik** [comment] 2015-04-11 22:13
So there is an additional option to get the behavior you are describing, if you pass `updateOnEmptySelection: true` as an additional optional, the toolbar should always be displayed even with an empty selection.

Somewhere along the way I believe the static toolbar began always showing up, but this would have been an unintended side-effect.  Let me know if that option doesn't get the behavior you want.

**Comment by adrianorsouza** [comment] 2015-04-11 23:18
@nmielnik by passing the option `updateOnEmptySelection: true` along with `staticToolbar: true` works flawlessly as I expected. Thanks
